In [105]:
# Q1 
X= 2000
while 1900 < X < 3200:
    if X % 5 ==0:
        if X % 7 == 0:
            print(X)
    X = X+1
        

2030
2065
2100
2135
2170
2205
2240
2275
2310
2345
2380
2415
2450
2485
2520
2555
2590
2625
2660
2695
2730
2765
2800
2835
2870
2905
2940
2975
3010
3045
3080
3115
3150
3185


In [20]:
# Q2: 
Y = int(input())
Z = 1
while Y > 1:
    Z = Z * Y
    Y = Y-1
print(Z)

5
120


In [46]:
# Q3: 
I = int(input())
MyDict={}
F = 1
while I >= 1:
    F = I * I
    MyDict.update({I:F})
    I = I-1
    F=1
print(MyDict)

4
{4: 16, 3: 9, 2: 4, 1: 1}


In [113]:
#Q4: 

S = input("Word: ")
L = [C for C in S]
print(L)

R = int(input("Which CH want to reomve: "))
L.pop(R)
print(''.join(L))

Word: Mohamed
['M', 'o', 'h', 'a', 'm', 'e', 'd']
Which CH want to reomve: 1
Mhamed


In [86]:
# Q5: 
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [92]:
# Q6: 
Y= np.arange(6).reshape(2, 3)
print(Y)
np.cov(Y) 


[[0 1 2]
 [3 4 5]]


array([[1., 1.],
       [1., 1.]])

In [104]:
Q7: 
import math
lst = []
n = int(input("Enter number of elements : "))
for i in range(0, n):
    ele = int(input('D: '))
    C= 50 
    H=30 
    Q = math.sqrt(((2 * C * D)/H))
    print(Q)
 
    lst.append(ele)


Enter number of elements : 3
D: 20
12.909944487358056
D: 12
12.909944487358056
D: 30
12.909944487358056
